### ISSUE TITLE
Support policy for step-issuer

### ISSUE THREAD

**Issue by shazib-summar** [smallstep/step-issuer#142]
Hello, is there any official support policy for step-issuer? 

By support I mean bug fixes by patch releases in older releases e.g. N-2 minor releases where N is the latest minor of the latest major version.

Thanks.

**Comment by dopey** [comment]
Hey @shazib-summar 👋 - apologies for the very long radio silence.

We don't offer an open source support policy for this project. We do bug / dependabot patches as needed, but everything is best effort. We do offer support for commercial customers; those interested
