### ISSUE TITLE
Support including intermediate CA certificates in leaf chain

### ISSUE THREAD

**Issue by wranders** [smallstep/step-issuer#16]
### Problem
When `step-certificates` is signed by an intermediate, and that certificate is appended to the issued CA certificate, the full chain is not included in certificates issued by `step-issuer`.

### Expected Result
Leaf certificates issued to services:

```sh
-----BEGIN CERTIFICATE-----
Leaf certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Step CA certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Intermediate CA certificate
-----END CERTIFICATE-----
```

### Actual Result
Leaf certificates issued to services:

```sh
-----BEGIN CERTIFICATE-----
Leaf certificate
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
Step CA certificate
-----END CERTIFICATE-----
```

This results in a broken chain of trust for services.

### Environment
Both `step-certificates` (`v0.17.3`) and `step-issuer` (`v0.5.1`) are installed via Helm to a `k3s` cluster.

---

At the request of @maraino via Discord, this issue is to track changing the API to include intermediate certificates.

**Comment by maraino** [comment]
As I mention in discord, the problem is that `step-issuer` is using the old API response that didn't have support for intermediate certs. I would push an update to read the intermediates from the new property.

**Comment by wranders** [comment]
https://github.com/smallstep/step-issuer/blob/cc45674b31f9f812850b0e2eca87c8eb37f7caaa/provisioners/step.go#L182-L193

If I'm understanding this right, there should just be a loop over `resp.CertChainPEM`, running `encodeX509` and appending the cert. The Root shouldn't be included here to muck things up, unless I missed something?

**Comment by maraino** [comment]
@wranders Yes, I believe that's the change. I was about to get into that.

**Comment by wranders** [comment]
Was working on a PR and had some questions, but just saw your PR which answered them.
Thanks for the work!

**Comment by maraino** [comment]
@wranders step-issuer v0.6.0 supports multiple intermediates, I've also published a new helm chart for it.

**Comment by wranders** [comment]
Fantastic! Thanks for knocking that out.
