### ISSUE TITLE
Are we still cutting GH release tags and publishing images?

### ISSUE THREAD

**Issue by mamccorm** [smallstep/step-issuer#171]
Hi there,

Looks like the last release tag was cut back in August 2023, and similarly this was the date of the last image push to dockerhub.

Is the project planning on creating new releases in future and still actively being maintained? I see commits to main since then, but no releases as yet

**Comment by dopey** [comment]
Hey @mamccorm 👋. Thanks for opening the issue!

Our policy (or lack thereof) with open source releases is to wait until there are features or bug fixes worthy of publishing a new version. The last 6+ months of history for `step-issuer` is almost entirely `go mod` package updates. We are actively maintaining the project - but there haven't been any features or bug fixes that our team has deemed worthy of prioritization recently. If there are features the community would like to see, we welcome PRs and Issues.

Anyway, we agree that the dependency updates certainly have value and seem worthy of a release. I'll see if I can get that done today.

**Comment by mamccorm** [comment]
Hey @dopey, appreciate the response and thanks for confirming. New release would be great, even if just to bucket up some vuln bumps. Appreciate all you do

**Comment by dopey** [comment]
Tried to make the 0.9.0 release and it failed due to a vulnerability from a dependency in an older version of `step-ca`. We are in the process of releasing `step-ca` (either today or tomorrow). Once that goes out, I'll upgrade the dependency here and cut a new release.

**Comment by mamccorm** [comment]
Appreciate the update

**Comment by developer-guy** [comment]
Any updates on this?

**Comment by dopey** [comment]
0.9.1 Was released last Thursday. I'll look into making a helm-chart release either today or tomorrow.

**Comment by dopey** [comment]
Believe the helm-charts are out now. Please let us know if you see any issues.
