### ISSUE TITLE
unparseable errors

### ISSUE THREAD

**Issue by wzrdtales** [smallstep/step-issuer#24]
hey there,

please release a new version with better errors (already here but not included in step-issuer yet): https://github.com/Cpcrook/certificates/blob/11637b57930cae1a4fa2c4fda1acc6ffed969863/ca/provisioner.go#L158

This bitten a customer of us today and is hard to debug

**Comment by maraino** [comment]
@wzrdtales Do you mean to update the version of step certificates dependency?

**Comment by maraino** [comment]
I believe it's fixed with the v0.6.1 and new helm chart. The dependency with certificates has been updated to the latest version.

**Comment by wzrdtales** [comment]
:+1:
