### ISSUE TITLE
Bug: unable to use step-issuer with cert-manager v0.14

### ISSUE THREAD

**Issue by charri** [smallstep/step-issuer#4]
cert-manager [v0.14.0](https://github.com/jetstack/cert-manager/releases/tag/v0.14.0) was released ca 6 days ago:.

With that release, `v1alpha1` was removed from cert-manager's custom resources. Applications must now support either `v1apha2 `or `v1apha3`.

When using the current deployment, the following error is shown in the logs of `smallstep/step-issuer:0.1.0`

```
ERROR controller-runtime.source if kind is a CRD, it should be installed before calling Start {"kind": "CertificateRequest.certmanager.k8s.io", "error": "no matches for kind \"CertificateRequest\" in version \"certmanager.k8s.io/v1alpha1\""}
```

I believe this issue should be resolved with an existing merge-request
#3 (Add support fort cert-manager v0.11.0+)

**Comment by maraino** [comment]
This should be fixed with the current version in `master` v0.2.0
