### ISSUE TITLE
Add support for Helm deployment

### ISSUE THREAD

**Issue by fauzanrazandi** [smallstep/step-issuer#8]
Any chance for Helm deployment support? If yes, then I am willing to work on it.

**Comment by maraino** [comment]
Hi @fauzanrazandi, yes, it's something pending that we need to add. Currently, we only have helm support for certificates and autocert.

I'm gonna add this issue to our product backlog for prioritization.

**Comment by sourishkrout** [comment]
@fauzanrazandi if you want to submit a pull request to add a helm chart please go ahead! Contributions are very welcome.

**Comment by fauzanrazandi** [comment]
Hi @sourishkrout, we just create a pull request on [this link](https://github.com/smallstep/helm-charts/pull/20). We're looking forward for your responses, thanks!
