### ISSUE TITLE
Add support to sign intermediate certificates

### ISSUE THREAD

**Issue by maraino** [smallstep/step-issuer#9]
### Description

Now that `step-ca` v0.15.x has support for signing intermediate certificates, it would be possible to create templates that sign an intermediate certificate, using custom templates with user-provided variables or supporting different providers.

**Comment by derveloper** [comment]
if I remove [this code](https://github.com/smallstep/step-issuer/blob/master/controllers/certificaterequest_controller.go#L107-L110), I can sign an intermediate certificate just fine
